spring.application.name=skribbl-clone

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/skribbl_clone}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173,http://localhost:5174}
